### ISSUE TITLE
SoftU2F is not detected as USB device

### ISSUE THREAD

**Issue by andy-dicki** [danstiner/rust-u2f#45] opened 2019-03-02 10:24 UTC
SoftU2F is not detected as USB device, but in dmesg it is an "USB HID" device.

**Comment by danstiner** [comment] 2019-03-02 18:42
Ahh okay this actually makes sense and is expected behavior but I had never thought about it.

I use the Linux UHID driver to create a virtual HID device.  You can think of USB HID as a separate protocol only certain USB devices support. Since this UHID devices do not support the full USB protocol, the kernel does not expose them as a USB devices.

**Comment by danstiner** [comment] 2019-04-04 03:57
Closing as expected behavior.

**Closed by danstiner** 2019-04-04 03:57 UTC
